# ==============================================================================
# Multi-Modal RNA-Seq Analysis Environment (Cancer Genomics)
#
# Enhanced environment for comprehensive cancer RNA-seq analysis including:
# - Somatic variant discovery
# - lncRNA profiling
# - miRNA analysis
# - Integrated multi-modal interpretation
#
# Usage: conda env create -f environment_multimodal.yml
# ==============================================================================

name: rnaseq-multimodal
channels:
  - conda-forge
  - bioconda
  - defaults
  - r

dependencies:
  # === CORE PYTHON ENVIRONMENT ===
  - python=3.9
  - pip
  - setuptools
  - wheel

  # === BASIC RNA-SEQ TOOLS ===
  - fastqc=0.11.9
  - fastp=0.23.2
  - multiqc=1.14
  - trimmomatic=0.39

  # === ALIGNMENT TOOLS ===
  - star=2.7.10a
  - bowtie=1.3.1      # For small RNA alignment
  - bowtie2=2.5.0
  - bwa=0.7.17
  - hisat2=2.2.1

  # === SAM/BAM PROCESSING ===
  - samtools=1.17
  - picard=3.0.0
  - bamtools=2.5.2

  # === VARIANT CALLING STACK ===
  - gatk4=4.4.0.0
  - bcftools=1.17
  - vcftools=0.1.16
  - htslib=1.17

  # === QUANTIFICATION TOOLS ===
  - subread=2.0.3        # featureCounts
  - salmon=1.9.0
  - kallisto=0.48.0
  - htseq=2.0.2

  # === SMALL RNA ANALYSIS ===
  - mirdeep2=0.1.3
  - cutadapt=4.4
  - viennarna=2.5.1
  - randfold=2.0.1

  # === WORKFLOW MANAGEMENT ===
  - snakemake=7.18.2
  - snakemake-minimal=7.18.2

  # === R ENVIRONMENT ===
  - r-base=4.2.0
  - r-essentials
  - r-devtools
  - r-tidyverse
  - r-ggplot2
  - r-pheatmap
  - r-rcolorbrewer
  - r-ggrepel
  - r-plotly
  - r-dt
  - r-htmlwidgets
  - r-reshape2
  - r-dplyr
  - r-tibble

  # === BIOCONDUCTOR CORE ===
  - bioconductor-biobase=2.58.0
  - bioconductor-biocgenerics=0.44.0
  - bioconductor-s4vectors=0.36.0
  - bioconductor-iranges=2.32.0
  - bioconductor-genomicranges=1.50.0
  - bioconductor-genomicfeatures=1.50.0
  - bioconductor-genomicalignments=1.34.0

  # === DIFFERENTIAL EXPRESSION ===
  - bioconductor-deseq2=1.38.0
  - bioconductor-edger=3.40.0
  - bioconductor-limma=3.54.0
  - bioconductor-tximport=1.26.0
  - bioconductor-tximeta=1.16.0

  # === VARIANT ANALYSIS ===
  - bioconductor-variantannotation=1.44.0
  - bioconductor-genomicscores=2.10.0
  - bioconductor-bsgenome=1.66.0
  - bioconductor-bsgenome.hsapiens.ucsc.hg38=1.4.4

  # === FUNCTIONAL ANALYSIS ===
  - bioconductor-clusterprofiler=4.6.0
  - bioconductor-enrichplot=1.18.0
  - bioconductor-dose=3.24.0
  - bioconductor-gosemsim=2.24.0
  - bioconductor-pathview=1.38.0

  # === ORGANISM DATABASES ===
  - bioconductor-org.hs.eg.db=3.16.0
  - bioconductor-org.mm.eg.db=3.16.0
  - bioconductor-annotationdbi=1.60.0
  - bioconductor-annotationhub=3.6.0

  # === PYTHON DATA SCIENCE ===
  - numpy=1.24.0
  - pandas=1.5.3
  - scipy=1.10.0
  - matplotlib=3.6.0
  - seaborn=0.12.0
  - plotly=5.17.0
  - scikit-learn=1.2.0
  - networkx=3.0

  # === PYTHON BIOINFORMATICS ===
  - biopython=1.81
  - pysam=0.21.0
  - pydeseq2=0.3.2
  - pybedtools=0.9.0

  # === JUPYTER ENVIRONMENT ===
  - jupyter
  - jupyterlab
  - notebook
  - ipywidgets

  # === UTILITIES ===
  - wget
  - curl
  - unzip
  - gzip
  - parallel
  - tree
  - htop
  - rsync

  # === PIP PACKAGES ===
  - pip:
    # Enhanced Python packages
    - pydeseq2>=0.3.2
    - gseapy>=1.0.4
    - upsetplot>=0.7.0
    - adjustText>=0.7.3
    - statannotations>=0.2.3

    # Variant analysis
    - cyvcf2>=0.30.0
    - pysam>=0.21.0

    # Small RNA analysis
    - mirdeep>=0.1.0

    # Network analysis
    - networkx>=3.0
    - igraph>=0.10.0
    - python-louvain>=0.16

    # Visualization enhancements
    - plotnine>=0.10.0
    - bokeh>=3.0.0

    # Cancer genomics specific
    - maftools>=0.1.0