# ==============================================================================
# Main Conda Environment for RNA-Seq Analysis Pipeline
#
# This environment contains all tools needed for the complete pipeline
# Usage: conda env create -f environment.yml
# ==============================================================================

name: rnaseq-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # === CORE PYTHON ENVIRONMENT ===
  - python=3.9
  - pip
  - setuptools
  - wheel

  # === QUALITY CONTROL TOOLS ===
  - fastqc=0.11.9
  - fastp=0.23.2
  - multiqc=1.14

  # === ALIGNMENT AND MAPPING ===
  - star=2.7.10a
  - bowtie2=2.5.0  # Alternative aligner
  - bwa=0.7.17     # Alternative aligner

  # === BAM/SAM PROCESSING ===
  - samtools=1.17
  - picard=3.0.0

  # === QUANTIFICATION ===
  - subread=2.0.3    # Contains featureCounts
  - salmon=1.9.0     # Alternative quantification
  - kallisto=0.48.0  # Alternative quantification

  # === R ENVIRONMENT ===
  - r-base=4.2.0
  - r-essentials
  - r-devtools
  - r-tidyverse
  - r-ggplot2
  - r-pheatmap
  - r-rcolorbrewer
  - r-ggrepel
  - r-plotly
  - r-dt
  - r-htmlwidgets

  # === BIOCONDUCTOR PACKAGES ===
  - bioconductor-deseq2=1.38.0
  - bioconductor-edger=3.40.0
  - bioconductor-limma=3.54.0
  - bioconductor-clusterprofiler=4.6.0
  - bioconductor-org.hs.eg.db=3.16.0
  - bioconductor-org.mm.eg.db=3.16.0
  - bioconductor-annotationdbi=1.60.0
  - bioconductor-genomicfeatures=1.50.0
  - bioconductor-genomicalignments=1.34.0
  - bioconductor-rsubread=2.12.0

  # === WORKFLOW MANAGEMENT ===
  - snakemake=7.18.2
  - snakemake-minimal=7.18.2

  # === PYTHON DATA SCIENCE ===
  - numpy=1.24.0
  - pandas=1.5.3
  - scipy=1.10.0
  - matplotlib=3.6.0
  - seaborn=0.12.0
  - plotly=5.17.0
  - scikit-learn=1.2.0

  # === PYTHON BIOINFORMATICS ===
  - biopython=1.81
  - pysam=0.21.0
  - pydeseq2=0.3.2
  - gseapy=1.0.4
  - scanpy=1.9.0

  # === UTILITIES ===
  - wget
  - curl
  - unzip
  - gzip
  - parallel
  - tree
  - htop

  # === JUPYTER ENVIRONMENT ===
  - jupyter
  - jupyterlab
  - notebook
  - ipywidgets

  # === CONTAINERIZATION ===
  - conda-pack

  # === PIP PACKAGES ===
  - pip:
    # Additional Python packages not available in conda
    - pydeseq2>=0.3.2
    - gseapy>=1.0.4
    - upsetplot>=0.7.0
    - adjustText>=0.7.3
    - statannotations>=0.2.3